task: &task box # box, segment

num_processes: 1

model: yolo
data: coco
epochs: 3
close_mosaic: 2
workers: 8
batch_size: &batch_size 8
cache: &cache True
prefetch: 4
shuffle: True
image_size: &image_size [640, 640]
constant: &constant 0 # (0-255) it can be list

preprocess:
  read_image: *cache

augmentation:
  mosaic: *image_size # (image_size)
  random_perspective: [15, 0.1, 0.5, 0, 0] #(rotate(15), translate(0.1), scale(0.5), shear(0), perspective(0))
  random_hsv: [0.15, 0.7, 0.4] # (+/- H, S, V)
  flip_ud: 0.0 # (prob)
  flip_lr: 0.5 # (prob)

process:
  resize_padding: [*image_size, True, *constant] # (image_size, center, constant) without mosaic
  unsqueeze_coords: True
  filter: 0.01
  segment_to_task: *task

postprocess:
  batch: *task
  normalize: True
  
