[project]
name = "uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gdown>=5.2.0",
    "matplotlib>=3.10.3",
    "nvidia-ml-py>=12.0.0",
    "numpy>=1.26.4",
    "onnx>=1.16.0",
    "opencv-python>=4.11.0.86",
    "openvino>=2024.0",
    "pillow>=11.2.1",
    "psutil>=5.0.0",
    "pycocotools>=2.0.10",
    "pyyaml>=6.0.2",
    "scipy>=1.15.3",
    "tensorflow==2.18.1",
    "tf_keras>=2.16",
    "tensorflow-datasets>=4.9.9",
    "tf2onnx>=1.16.0",
    "tqdm>=4.67.1",
    "tensorrt-cu12>=10.0",
]
